Entire development of NYT clone
karmaester/NYT-Article-Cloned pull request #1
Opened 2020-08-20 19:47 UTC by martinnajjar12

### NYT Clone
We've used the techs below to create this website:

- HTML5
- CSS3
- Linters

2020-08-20 21:13 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

  ### Hi team, you guys did a very good job so far!
  #### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
- [x] Guys, it should have a "Hamburger button", please implement that with a `<button>` tag (link to page) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)
- [x] Remember to make a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/))
- [x] Files not related to the project should not be committed and added to .gitignore (e.g. package.json and package-lock.json) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] It should have a `<footer>` with fixed  position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)**
- [x] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)
- [x] Kindly remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/90824661-23545c80-e30e-11ea-9030-9cb1a614f9e0.png)
- [x] Please add a live demo link. (You can use [Raw Githack](https://raw.githack.com/), for example.)



## [OPTIONAL CHANGES]
- [ ] Put your `css` files in a css folder. (To make your repo more professional)

## Summary
✨ Good job with that project, it looks really good for a first review 💥
✨ Well done implementing `flex`, `grid` and `float` ! The layout looks almost the same.
## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>
<sub>**Some Students aren't being able to see the sticky footer, use [this](https://user-images.githubusercontent.com/56762529/90828132-dd9a9280-e313-11ea-8a52-9d4cbefbedc6.png) image as a guide
 </sub>

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  text-decoration: none;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
For example: Group all the rules that are common to all the anchor tags:
![image](https://user-images.githubusercontent.com/56762529/90825506-65ca6900-e30f-11ea-9619-83a671c99be7.png)

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  width: 100%;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  width: 100%;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  width: 100%;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  width: 100%;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  width: 100%;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-20 21:13 UTC, kevincappuccino commented on styles.css
> +  width: 100%;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-21 17:14 UTC, martinnajjar12 commented
> # [STATUS] CHANGES REQUIRED♻️
> ### Hi team, you guys did a very good job so far!
> #### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:
> _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
> 
> ## [REQUIRED CHANGES]
> * [x]  Guys, it should have a "Hamburger button", please implement that with a `<button>` tag (link to page) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)
> * [x]  Remember to make a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/))
> * [x]  Files not related to the project should not be committed and added to .gitignore (e.g. package.json and package-lock.json) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> * [x]  It should have a `<footer>` with fixed  position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)**
> * [x]  The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)
> * [x]  Kindly remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
>   Take a look at this example:
>   ![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
>   Your HTML will be something like this:
>   ![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
>   Apply the same logic above in **ALL** those repeated rules listed below:
>   ![image](https://user-images.githubusercontent.com/56762529/90824661-23545c80-e30e-11ea-9030-9cb1a614f9e0.png)
> * [x]  Please add a live demo link. (You can use [Raw Githack](https://raw.githack.com/), for example.)
> 
> ## [OPTIONAL CHANGES]
> * [ ]  Put your `css` files in a css folder. (To make your repo more professional)
> 
> ## Summary
> ✨ Good job with that project, it looks really good for a first review 💥
> ✨ Well done implementing `flex`, `grid` and `float` ! The layout looks almost the same.
> 
> ## Please make the required changes and resubmit for a new code review once you are ready💪
> ## As always, I wish you all the very best and see you both at the top🚀
> 👨🏻‍💻 **TSE: Kevin Alves**
> 
> 📫 Have any question? Better call Kevin:
> 
> [ ![gmail](https://camo.githubusercontent.com/c4a0060eefb5b424cd205fb52a5e5040d105605e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f676d61696c2d2532302d20677265656e3f6c6f676f3d676d61696c267374796c653d736f6369616c)](mailto:kevinalves.js@gmail.com) [![Twitter Follow](https://camo.githubusercontent.com/79f7a1b89e79a6a1845a536be84aeb89ad1d1bcd/68747470733a2f2f696d672e736869656c64732e696f2f747769747465722f666f6c6c6f772f6b6576696e6e6e6d6e3f7374796c653d736f6369616c)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://camo.githubusercontent.com/58a600b84c266fe0a6a23f055116e3561f2ed08b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f536c61636b2d4b6576696e253230416c7665732d677265656e3f6c6f676f3d736c61636b267374796c653d736f6369616c)](https://microverse-students.slack.com/team/UT86D3AP4)
> 
> *We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.
> **Some Students aren't being able to see the sticky footer, use [this](https://user-images.githubusercontent.com/56762529/90828132-dd9a9280-e313-11ea-8a52-9d4cbefbedc6.png) image as a guide

Thank you for your review, We really appreciate it :)

2020-08-21 20:06 UTC, SpaYco requested changes
# Changes Requested 

Hello Team! 👋 

Awesome job so far!! 👍 good job implementing the changes, you forgot one though! 

## Required Changes ♻️ 

- [x]  Files not related to the project should not be committed and added to .gitignore (e.g. package.json and package-lock.json) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) (Hint: Use `git rm file_name`)

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-21 20:08 UTC, SpaYco commented
### Please note, if you wanna remove the files from GitHub, but keep it locally, use .gitignore then [follow this](https://stackoverflow.com/questions/3469741/remove-file-from-the-repository-but-keep-it-locally)

2020-08-21 20:16 UTC, SpaYco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-21 20:18 UTC, merged